Transform: AWS::Serverless-2016-10-31
Description: Macro for cloudformation

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./index.js
      Handler: index.handler
      Runtime: nodejs8.10

  Macro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: MultiplexResourceMacro
      FunctionName: !GetAtt Function.Arn
